// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdvyrcefqoycgsqgxbhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkdnlyY2VmcW95Y2dzcWd4Ymh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTM4MzgsImV4cCI6MjA2NDE4OTgzOH0.sOuVkJexjdzATtJcE6vMtzhdp3wbj0C7bE5gXZXQ15U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);